In [1]:
import os

print(os.getcwd())
print(os.listdir())

c:\Users\Pavan\AquaPulse\backend\models
['AquaPulse_Data_Exploration.ipynb', 'dristhi_water_quality_model.pkl', 'schemas.py', '__init__.py', '__pycache__']

In [2]:
import os

os.listdir()

['AquaPulse_Data_Exploration.ipynb',
 'dristhi_water_quality_model.pkl',
 'schemas.py',
 '__init__.py',
 '__pycache__']

In [3]:
import os

for root, dirs, files in os.walk("dataset"):
    print(root)
    for file in files:
        print("   ", file)

In [4]:
import importlib
import os

importlib.reload(os)
print(os.path.exists("..//..data/WQD.xlsx"))

False

In [5]:
import pandas as pd

df = pd.read_excel("../../data/WQD.xlsx")

df.head()

,Temp,Turbidity (cm),DO(mg/L),BOD (mg/L),CO2,pH`,Alkalinity (mg L-1 ),Hardness (mg L-1 ),Calcium (mg L-1 ),Ammonia (mg L-1 ),Nitrite (mg L-1 ),Phosphorus (mg L-1 ),H2S (mg L-1 ),Plankton (No. L-1),Water Quality
0,67.448725,10.127148,0.208153,7.473607,10.181084,4.751657,218.364855,300.125080,337.178226,0.286054,4.355310,0.005984,0.066793,6069.624017,2
1,64.626666,94.015595,11.434463,10.859998,14.860521,3.085154,273.939692,8.426776,363.660740,0.096040,2.182753,0.004906,0.023428,250.995959,2
2,65.121842,90.653462,12.430865,12.809970,12.319980,9.648515,220.812730,11.726274,309.370934,0.974501,4.901760,0.006979,0.065041,7218.927473,2
3,1.640334,0.066344,10.963529,8.508023,12.955209,4.819988,266.571628,6.627655,8.180468,0.884865,3.571842,3.174473,0.026018,1230.062252,2
4,64.863434,2.119173,1.361736,13.335372,13.603197,10.244034,252.108000,339.891514,253.996871,0.801695,4.655898,3.854701,0.060995,1035.054820,2

In [6]:
df.shape

(4300, 15)

In [7]:
df.columns

Index(['Temp', 'Turbidity (cm)', 'DO(mg/L)', 'BOD (mg/L)', 'CO2', 'pH`',
       'Alkalinity (mg L-1 )', 'Hardness (mg L-1 )', 'Calcium (mg L-1 )',
       'Ammonia (mg L-1 )', 'Nitrite (mg L-1 )', 'Phosphorus (mg L-1 )',
       'H2S (mg L-1 )', 'Plankton (No. L-1)', 'Water Quality'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4300 entries, 0 to 4299
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Temp                  4300 non-null   float64
 1   Turbidity (cm)        4300 non-null   float64
 2   DO(mg/L)              4300 non-null   float64
 3   BOD (mg/L)            4300 non-null   float64
 4   CO2                   4300 non-null   float64
 5   pH`                   4300 non-null   float64
 6   Alkalinity (mg L-1 )  4300 non-null   float64
 7   Hardness (mg L-1 )    4300 non-null   float64
 8   Calcium (mg L-1 )     4300 non-null   float64
 9   Ammonia (mg L-1 )     4300 non-null   float64
 10  Nitrite (mg L-1 )     4300 non-null   float64
 11  Phosphorus (mg L-1 )  4300 non-null   float64
 12  H2S (mg L-1 )         4300 non-null   float64
 13  Plankton (No. L-1)    4300 non-null   float64
 14  Water Quality         4300 non-null   int64
dtypes: float64(14), int64(1)
memory usage: 504.0 KB

In [9]:
df.describe()

,Temp,Turbidity (cm),DO(mg/L),BOD (mg/L),CO2,pH`,Alkalinity (mg L-1 ),Hardness (mg L-1 ),Calcium (mg L-1 ),Ammonia (mg L-1 ),Nitrite (mg L-1 ),Phosphorus (mg L-1 ),H2S (mg L-1 ),Plankton (No. L-1),Water Quality
count,4300.000000,4300.000000,4300.000000,4300.000000,4300.000000,4300.000000,4300.000000,4300.000000,4300.000000,4300.000000,4300.000000,4300.000000,4300.000000,4300.000000,4300.000000
mean,25.695663,39.046681,5.300346,3.125079,6.375929,7.713468,93.717183,127.055476,84.871932,0.048269,0.642948,1.172749,0.016473,3805.510620,1.023256
std,9.670202,20.942726,1.832736,2.292060,2.831104,1.580282,68.949048,78.883091,75.718842,0.122886,0.903592,1.082648,0.011874,1208.547783,0.820996
min,0.194046,0.051424,0.133928,1.000621,0.001155,0.003944,25.012328,0.255805,0.018293,0.000001,0.000025,0.000128,0.000002,78.603733,0.000000
25%,19.775926,22.224140,3.978366,1.522077,5.048761,6.443019,40.422364,69.479620,23.745078,0.012750,0.010636,0.028355,0.010072,2956.020049,0.000000
50%,25.041849,30.205696,5.000754,2.236022,6.598076,7.743176,67.562607,111.063301,62.845419,0.026335,0.099908,0.975312,0.019049,3729.396476,1.000000
75%,30.277718,55.945735,6.521225,4.324578,8.241532,9.035251,132.834386,162.675648,115.596833,0.039016,1.166714,2.101317,0.019567,4555.089727,2.000000
max,84.251522,99.797743,14.970122,14.943006,14.984216,14.851195,299.913160,398.796550,399.321398,0.999300,4.989535,4.974457,0.099220,7460.415789,2.000000

In [10]:
df.isnull().sum()

Temp                    0
Turbidity (cm)          0
DO(mg/L)                0
BOD (mg/L)              0
CO2                     0
pH`                     0
Alkalinity (mg L-1 )    0
Hardness (mg L-1 )      0
Calcium (mg L-1 )       0
Ammonia (mg L-1 )       0
Nitrite (mg L-1 )       0
Phosphorus (mg L-1 )    0
H2S (mg L-1 )           0
Plankton (No. L-1)      0
Water Quality           0
dtype: int64

In [11]:
df["Water Quality"].value_counts()

Water Quality
2    1500
1    1400
0    1400
Name: count, dtype: int64

In [12]:
import matplotlib.pyplot as plt

df["Water Quality"].value_counts().sort_index().plot(
    kind="bar",
    figsize=(8,5)
)

plt.title("Water Quality Classes")
plt.xlabel("Class")
plt.ylabel("Number of Samples")
plt.grid(axis="y")
plt.show()

In [13]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(14,10))

sns.heatmap(
    df.corr(),
    cmap="coolwarm",
    annot=False
)

plt.title("Feature Correlation Heatmap")
plt.show()

In [14]:
import seaborn as sns

plt.figure(figsize=(12,6))

sns.boxplot(data=df)

plt.xticks(rotation=90)

plt.show()

In [15]:
from sklearn.model_selection import train_test_split

X = df[
    [
        "Temp",
        "pH`",
        "DO(mg/L)",
        "Turbidity (cm)",
    ]
]
y = df["Water Quality"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", X_train.shape)
print("Testing samples :", X_test.shape)

Training samples: (3440, 4)
Testing samples : (860, 4)

In [16]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train, y_train)

print("Training Completed!")

Training Completed!

In [17]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

pred = rf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

print(classification_report(y_test, pred))

Accuracy: 0.8965116279069767
              precision    recall  f1-score   support

           0       0.89      0.96      0.92       280
           1       0.88      0.97      0.93       280
           2       0.92      0.77      0.84       300

    accuracy                           0.90       860
   macro avg       0.90      0.90      0.90       860
weighted avg       0.90      0.90      0.89       860

In [18]:
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, pred)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues"
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Random Forest Confusion Matrix")

plt.show()

In [19]:
print("="*50)
print("Model Comparison")
print("="*50)

==================================================
Model Comparison
==================================================

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score

models = {
    "Logistic Regression": LogisticRegression(max_iter=500),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=200, random_state=42),
    "KNN": KNeighborsClassifier(),
    "SVM": SVC()
}

results = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    acc = accuracy_score(y_test, pred)
    results[name] = acc
    print(f"{name}: {acc:.4f}")

Logistic Regression: 0.6767
Decision Tree: 0.8256
Random Forest: 0.8965
KNN: 0.8302
SVM: 0.7686

In [21]:
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.bar(results.keys(), results.values())

plt.ylabel("Accuracy")
plt.title("Model Comparison")

plt.xticks(rotation=20)

plt.show()

In [22]:
import pandas as pd

feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)

feature_importance

          Feature  Importance
2        DO(mg/L)    0.324350
3  Turbidity (cm)    0.310803
0            Temp    0.199716
1             pH`    0.165131

In [23]:
import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))

plt.barh(
    feature_importance["Feature"],
    feature_importance["Importance"]
)

plt.gca().invert_yaxis()

plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("Random Forest Feature Importance")

plt.show()

In [24]:
import joblib

joblib.dump(rf, "dristhi_water_quality_model.pkl")

print("Model Saved Successfully!")

Model Saved Successfully!

In [25]:
loaded_model = joblib.load("dristhi_water_quality_model.pkl")

print("Model Loaded Successfully!")

Model Loaded Successfully!

In [26]:
sample = X_test.iloc[[0]]

prediction = loaded_model.predict(sample)

print("Predicted Class:", prediction[0])
print("Actual Class:", y_test.iloc[0])

Predicted Class: 1
Actual Class: 1

In [27]:
import shap

explainer = shap.TreeExplainer(rf)

print("SHAP Explainer Ready!")

c:\Users\Pavan\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

SHAP Explainer Ready!

In [28]:
import joblib

rf = joblib.load("dristhi_water_quality_model.pkl")

print("Random Forest Model Loaded!")

Random Forest Model Loaded!

In [29]:
shap_values = explainer.shap_values(X_test)

print("SHAP values calculated successfully!")

SHAP values calculated successfully!

In [30]:
shap.summary_plot(
    shap_values,
    X_test,
    feature_names=X_test.columns
)

In [31]:
sample = X_test.iloc[[0]]

shap.plots.waterfall(
    explainer(sample)[0, :, 0]
)

In [32]:
sample = X_test.iloc[[0]]

shap_values = explainer(sample)

shap.plots.waterfall(shap_values[0, :, 0])

In [33]:
shap.decision_plot(
    shap_values.base_values[0, 0],
    shap_values.values[0, :, 0],
    X_test.iloc[0],
    feature_names=list(X_test.columns)
)

In [34]:
shap.decision_plot(
    shap_values.base_values[0, 0],
    shap_values.values[0, :, 0],
    X_test.iloc[0].values,
    feature_names=list(X_test.columns)
)

In [35]:
class_idx = 0  # Try class 0 first

shap.decision_plot(
    shap_values.base_values[0, class_idx],
    shap_values.values[0, :, class_idx],
    X_test.iloc[0].values,
    feature_names=list(X_test.columns)
)

In [36]:
print(df.columns.tolist())

['Temp', 'Turbidity (cm)', 'DO(mg/L)', 'BOD (mg/L)', 'CO2', 'pH`', 'Alkalinity (mg L-1 )', 'Hardness (mg L-1 )', 'Calcium (mg L-1 )', 'Ammonia (mg L-1 )', 'Nitrite (mg L-1 )', 'Phosphorus (mg L-1 )', 'H2S (mg L-1 )', 'Plankton (No. L-1)', 'Water Quality']

In [37]:
print(rf.score(X_test, y_test))

0.8965116279069767

In [38]:
import os
print(os.getcwd())

c:\Users\Pavan\AquaPulse\backend\models

In [39]:
import os
print(os.path.exists("dataset"))

False

In [40]:
import os
print(os.path.exists("dataset/Aquaculture - Water Quality Dataset"))

False

In [41]:
import os
print(os.path.exists("dataset/Aquaculture- Water Qualty Dataset/WQD.xlsx"))

False